# Generated by Django 5.1.7 on 2025-03-14 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklygrade',
            old_name='GradeID',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='weeklygrade',
            name='AlphabetGrade',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='weeklygrade',
            name='PercentileGrade',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weeklygrade',
            name='WeekNumber',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='weeklygrade',
            name='categorized_assignment_grades',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='weeklygrade',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.course'),
        ),
        migrations.AlterField(
            model_name='weeklygrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.student'),
        ),
        migrations.AlterModelTable(
            name='course',
            table=None,
        ),
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
        migrations.AlterModelTable(
            name='weeklygrade',
            table=None,
        ),
        migrations.CreateModel(
            name='AssignmentGroup',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('points_possible', models.FloatField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.course')),
                ('assignment_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.assignmentgroup')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.student')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
