# Generated by Django 5.1.7 on 2025-03-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_rename_gradeid_weeklygrade_id_alter_course_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklygrade',
            name='AlphabetGrade',
            field=models.CharField(max_length=10),
        ),
    ]
