# Generated by Django 5.1.7 on 2025-03-31 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0003_alter_weeklygrade_alphabetgrade'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assignmentgroup',
            name='group_weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='UNKNOWN', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='role',
            field=models.CharField(default='UNKNOWN', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='testApp.assignmentgroup'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='assignment_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='points_possible',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='assignmentgroup',
            name='group_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='weeklygrade',
            name='AlphabetGrade',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='weeklygrade',
            name='categorized_assignment_grades',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='weeklygrade',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.student')),
            ],
        ),
        migrations.DeleteModel(
            name='AssignmentSubmission',
        ),
    ]
