# Generated by Django 5.1.7 on 2025-03-31 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0004_alter_enrollment_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course', 'role')},
        ),
    ]
