# Generated by Django 5.1.7 on 2025-03-31 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0005_alter_enrollment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='current_grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='current_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
