# Generated by Django 5.1.7 on 2025-04-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0006_enrollment_current_grade_enrollment_current_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='term',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
