# Generated by Django 5.1.7 on 2025-04-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0008_alter_student_student_id_alter_student_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
