# Generated by Django 5.1.7 on 2025-04-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0009_alter_course_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='assignmentgroup',
            name='group_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
