# Generated by Django 5.1.7 on 2025-04-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0010_alter_assignment_assignment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='points_possible',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
