# Generated by Django 5.1.7 on 2025-04-17 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0011_alter_assignment_points_possible'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklygrade',
            unique_together={('student', 'course', 'WeekNumber')},
        ),
    ]
