# Generated by Django 5.1.7 on 2025-04-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0012_alter_weeklygrade_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
